name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar lint
        run: npm run lint

      - name: Compilar aplicación
        run: npm run build

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_actions_montenegro
          chmod 600 ~/.ssh/github_actions_montenegro
          ssh-keyscan -p "${{ vars.SSH_PORT }}" "${{ vars.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Probar conexión SSH
        run: |
          ssh \
            -i ~/.ssh/github_actions_montenegro \
            -p "${{ vars.SSH_PORT }}" \
            "${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}" \
            "echo 'GitHub Actions conectado correctamente' && hostname && pwd"
      - name: Desplegar a producción
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/github_actions_montenegro -p ${{ vars.SSH_PORT }}" \
            dist/ \
            "${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:${{ vars.DEPLOY_PATH }}/"